# Problem 1

In [1]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])
C = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
E = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

A = np.row_stack([v1, v2, v3])
print('----A----\n', A, '\n---------', sep='')
B = np.column_stack([v1, v2, v3])
print('----B----\n', B, '\n---------', sep='')
D = np.column_stack([C, v3])
print('----D----\n', D, '\n---------', sep='')

print('E[0, 3] is', E[0, 3])
print('E[1, 2] is', E[1, 2])
print('E[0:2, 2] is', E[0:2, 2])
print('E[0:2, 2:4] is\n', E[0:2, 2:4], '\n---------', sep='')
print('E[2, :] is', E[2, :])
E[0, 0] = -1
print('E[0, 0] is', E[0, 0])

#print(D)

----A----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------
----B----
[[1 4 7]
 [2 5 8]
 [3 6 9]]
---------
----D----
[[1 2 7]
 [3 4 8]
 [5 6 9]]
---------
E[0, 3] is 4
E[1, 2] is 7
E[0:2, 2] is [3 7]
E[0:2, 2:4] is
[[3 4]
 [7 8]]
---------
E[2, :] is [ 9 10 11 12]
E[0, 0] is -1


# Problem 2

In [2]:
import numpy as np

A = np.array([
    [1., 2.],
    [3., 4.]
])
B = np.array([
    [2., 2.],
    [1., 3.]
])
C = np.array([
    [4., 5., 6.],
    [7., 8., 9.]
])
v = np.array([
    [10.],
    [20.]
])
D11 = np.array([
    [1., 2.],
    [3., 4.]
])
D12 = np.array([
    [5.],
    [6.]
])
D21 = np.array([7., 7.])
D22 = np.array([8.])

print('----A+B----\n', A + B, '\n---------', sep='')
print('----A-B----\n', A - B, '\n---------', sep='')
print('----3A----\n', 3 * A, '\n---------', sep='')
print('----2v----\n', 2 * v, '\n---------', sep='')
print('----AB----\n', np.matmul(A, B), '\n---------', sep='')
print('----AC----\n', np.matmul(A, C), '\n---------', sep='')
print('----Av----\n', np.dot(A, v), '\n---------', sep='')
print('----A^2----\n', np.linalg.matrix_power(A, 2), '\n---------', sep='')
print('----A^3----\n', np.linalg.matrix_power(A, 3), '\n---------', sep='')
print('----A*B 성분별----\n', np.multiply(A, B), '\n---------', sep='')
print('----A/B----\n', A / B, '\n---------', sep='')
print('----A^2 성분별----\n', A**2, '\n---------', sep='')
print('----A.T----\n', A.T, '\n---------', sep='')
print('----v.T----\n', v.T, '\n---------', sep='')
print('----diag(1,2,3)----\n', np.diag([1, 2, 3]), '\n---------', sep='')
D = np.block([
    [D11, D12],
    [D21, D22]
])
print('----D----\n', D, '\n---------', sep='')

----A+B----
[[3. 4.]
 [4. 7.]]
---------
----A-B----
[[-1.  0.]
 [ 2.  1.]]
---------
----3A----
[[ 3.  6.]
 [ 9. 12.]]
---------
----2v----
[[20.]
 [40.]]
---------
----AB----
[[ 4.  8.]
 [10. 18.]]
---------
----AC----
[[18. 21. 24.]
 [40. 47. 54.]]
---------
----Av----
[[ 50.]
 [110.]]
---------
----A^2----
[[ 7. 10.]
 [15. 22.]]
---------
----A^3----
[[ 37.  54.]
 [ 81. 118.]]
---------
----A*B 성분별----
[[ 2.  4.]
 [ 3. 12.]]
---------
----A/B----
[[0.5        1.        ]
 [3.         1.33333333]]
---------
----A^2 성분별----
[[ 1.  4.]
 [ 9. 16.]]
---------
----A.T----
[[1. 3.]
 [2. 4.]]
---------
----v.T----
[[10. 20.]]
---------
----diag(1,2,3)----
[[1 0 0]
 [0 2 0]
 [0 0 3]]
---------
----D----
[[1. 2. 5.]
 [3. 4. 6.]
 [7. 7. 8.]]
---------
